# Generated by Django 4.1.3 on 2022-11-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catigorizer_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='categories',
            field=models.ManyToManyField(null=True, to='catigorizer_api.categories', verbose_name='категории'),
        ),
    ]
